name: .NET Core CI/CD

on:
  push:
    branches:
      - master  # Change to 'main' if needed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x' # Change to your project version

    - name: Restore Dependencies
      run: dotnet restore

    - name: Build Project
      run: dotnet build --configuration Release --no-restore

    - name: Run Tests (if applicable)
      run: dotnet test --no-restore --verbosity normal

    - name: Publish App
      run: dotnet publish -c Release -o ./publish

    - name: Deploy (Example)
      run: echo "Deploying to server..."
